CREATE TABLE room (
	RoomID SERIAL UNIQUE NOT NULL PRIMARY KEY,
	RoomCap INTEGER NOT NULL
);

CREATE TABLE film (
	FilmID SERIAL UNIQUE NOT NULL PRIMARY KEY,
	FilmTitle CHAR(50) UNIQUE NOT NULL,
	FilmRelease DATE NOT NULL
);

CREATE TABLE role (
	RoleID SERIAL UNIQUE NOT NULL PRIMARY KEY,
	RoleName CHAR(50) NOT NULL
);

CREATE TABLE person (
	PersonID SERIAL UNIQUE NOT NULL PRIMARY KEY,
	PersonFirstName CHAR(50) NOT NULL,
	PersonLastName CHAR(50) NOT NULL
);

CREATE TABLE client (
	ClientID SERIAL UNIQUE NOT NULL PRIMARY KEY,
	ClientFirstName CHAR(50) NOT NULL,
	ClientLastName CHAR(50) NOT NULL,
	ClientAge INTEGER NOT NULL,
	ClientCity CHAR(50) NOT NULL
);

CREATE TABLE screening (
	ScreeningID SERIAL UNIQUE NOT NULL PRIMARY KEY,
	ScreeningRoom INTEGER NOT NULL REFERENCES room ON UPDATE CASCADE ON DELETE CASCADE,
	ScreeningFilm  INTEGER NOT NULL REFERENCES film ON UPDATE CASCADE ON DELETE CASCADE,
	ScreeningTimestamp INTEGER NOT NULL
);

CREATE TABLE staff (
	FilmIdRef INTEGER NOT NULL REFERENCES film ON UPDATE CASCADE ON DELETE CASCADE,
	RoleIdRef INTEGER NOT NULL REFERENCES role ON UPDATE CASCADE ON DELETE CASCADE,
	PersonRef INTEGER NOT NULL REFERENCES person ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY (FilmIdRef, RoleIdRef)
);

CREATE TABLE booking (
	BookingID SERIAL UNIQUE NOT NULL PRIMARY KEY,
	ClientRef INTEGER NOT NULL REFERENCES client ON UPDATE CASCADE ON DELETE RESTRICT,
	ScreeningRef INTEGER NOT NULL REFERENCES screening ON UPDATE CASCADE ON DELETE RESTRICT
);
